// src/lib/visual/ProximityGrid.svelte
<script lang="ts">
	export let columns = 11;
	export let rows = 7;
	export let color = '#405cff';
	export let reach = 170;

	let host: HTMLDivElement;
	let pointerX = -1000;
	let pointerY = -1000;
	let width = 1;
	let height = 1;

	$: cells = Array.from({ length: columns * rows }, (_, index) => ({
		index,
		column: index % columns,
		row: Math.floor(index / columns)
	}));

	function updatePointer(event: PointerEvent) {
		const bounds = host.getBoundingClientRect();
		width = bounds.width;
		height = bounds.height;
		pointerX = event.clientX - bounds.left;
		pointerY = event.clientY - bounds.top;
	}

	function proximity(column: number, row: number) {
		const cellX = ((column + 0.5) / columns) * width;
		const cellY = ((row + 0.5) / rows) * height;
		const distance = Math.hypot(pointerX - cellX, pointerY - cellY);
		return Math.max(0, Math.min(1, 1 - distance / reach));
	}
</script>

<div
	class="proximity-grid"
	bind:this={host}
	style={`--grid-columns: ${columns}; --grid-rows: ${rows}; --grid-color: ${color}`}
	on:pointermove={updatePointer}
	on:pointerleave={() => {
		pointerX = -1000;
		pointerY = -1000;
	}}
	aria-hidden="true"
>
	{#each cells as cell}
		{@const amount = proximity(cell.column, cell.row)}
		<i style={`--proximity: ${amount}; --cell-delay: ${(cell.index * 19) % 260}ms`} />
	{/each}
</div>

<style>
	.proximity-grid {
		display: grid;
		width: 100%;
		height: 100%;
		grid-template-columns: repeat(var(--grid-columns), 1fr);
		grid-template-rows: repeat(var(--grid-rows), 1fr);
	}

	i {
		position: relative;
		border-right: 1px solid color-mix(in srgb, var(--grid-color) 16%, transparent);
		border-bottom: 1px solid color-mix(in srgb, var(--grid-color) 16%, transparent);
		background: color-mix(
			in srgb,
			var(--grid-color) calc((7% + var(--proximity) * 60%)),
			transparent
		);
		transform: scale(calc(0.82 + var(--proximity) * 0.18));
		transition: background 160ms ease, transform 220ms cubic-bezier(0.2, 0.8, 0.2, 1);
		transition-delay: var(--cell-delay);
	}

	i::after {
		position: absolute;
		inset: 40%;
		background: var(--grid-color);
		border-radius: 50%;
		content: '';
		opacity: var(--proximity);
		transform: scale(calc(0.2 + var(--proximity)));
	}

	@media (prefers-reduced-motion: reduce) {
		i {
			transition: none;
		}
	}
</style>

// src/components/beautiful/proximity-grid/proximity-grid.tsx
'use client';

import { useEffect, useMemo, useRef, type HTMLAttributes, type PointerEvent } from 'react';
import type { CustomProperties } from '../types';
import './proximity-grid.css';

export type ProximityGridProps = HTMLAttributes<HTMLDivElement> & {
	columns?: number;
	rows?: number;
	color?: string;
	reach?: number;
};

export function ProximityGrid({
	columns = 11,
	rows = 7,
	color = '#405cff',
	reach = 170,
	className = '',
	style,
	...props
}: ProximityGridProps) {
	const hostRef = useRef<HTMLDivElement>(null);
	const cellRefs = useRef<Array<HTMLElement | null>>([]);
	const frameRef = useRef<number | null>(null);
	const pendingPointer = useRef({ x: 0, y: 0 });
	const safeColumns = Math.max(1, Math.min(24, Math.round(columns)));
	const safeRows = Math.max(1, Math.min(18, Math.round(rows)));
	const safeReach = Math.max(1, reach);
	const cells = useMemo(
		() =>
			Array.from({ length: safeColumns * safeRows }, (_, index) => ({
				index,
				column: index % safeColumns,
				row: Math.floor(index / safeColumns)
			})),
		[safeColumns, safeRows]
	);
	const gridStyle: CustomProperties = {
		'--grid-columns': safeColumns,
		'--grid-rows': safeRows,
		'--grid-color': color,
		...style
	};

	useEffect(
		() => () => {
			if (frameRef.current !== null) cancelAnimationFrame(frameRef.current);
		},
		[]
	);

	function draw(clientX: number, clientY: number) {
		const host = hostRef.current;
		if (!host) return;
		const bounds = host.getBoundingClientRect();
		const pointerX = clientX - bounds.left;
		const pointerY = clientY - bounds.top;
		cells.forEach((cell, index) => {
			const cellX = ((cell.column + 0.5) / safeColumns) * bounds.width;
			const cellY = ((cell.row + 0.5) / safeRows) * bounds.height;
			const proximity = Math.max(
				0,
				Math.min(1, 1 - Math.hypot(pointerX - cellX, pointerY - cellY) / safeReach)
			);
			cellRefs.current[index]?.style.setProperty('--proximity', `${proximity}`);
		});
	}

	function handlePointerMove(event: PointerEvent<HTMLDivElement>) {
		pendingPointer.current = { x: event.clientX, y: event.clientY };
		if (frameRef.current !== null) return;
		frameRef.current = requestAnimationFrame(() => {
			draw(pendingPointer.current.x, pendingPointer.current.y);
			frameRef.current = null;
		});
	}

	function resetCells() {
		cellRefs.current.forEach((node) => node?.style.setProperty('--proximity', '0'));
	}

	return (
		<div
			ref={hostRef}
			className={`bc-proximity-grid ${className}`.trim()}
			style={gridStyle}
			onPointerMove={handlePointerMove}
			onPointerLeave={resetCells}
			aria-hidden="true"
			{...props}
		>
			{cells.map((cell, index) => (
				<i
					ref={(node) => {
						cellRefs.current[index] = node;
					}}
					style={
						{
							'--proximity': 0,
							'--cell-delay': `${(cell.index * 19) % 260}ms`
						} as CustomProperties
					}
					key={cell.index}
				/>
			))}
		</div>
	);
}
