// src/lib/visual/FocusBeam.svelte
<script lang="ts">
	export let color = '#405cff';
	export let radius = 260;
	export let intensity = 0.18;

	let host: HTMLDivElement;
	let x = 50;
	let y = 50;
	let engaged = false;

	function updatePosition(event: PointerEvent) {
		const bounds = host.getBoundingClientRect();
		x = ((event.clientX - bounds.left) / bounds.width) * 100;
		y = ((event.clientY - bounds.top) / bounds.height) * 100;
		engaged = true;
	}

	function focusPosition(event: FocusEvent) {
		const target = event.target;
		if (!(target instanceof HTMLElement)) return;

		const bounds = host.getBoundingClientRect();
		const targetBounds = target.getBoundingClientRect();
		x = ((targetBounds.left + targetBounds.width / 2 - bounds.left) / bounds.width) * 100;
		y = ((targetBounds.top + targetBounds.height / 2 - bounds.top) / bounds.height) * 100;
		engaged = true;
	}
</script>

<div
	class="focus-beam"
	class:engaged
	bind:this={host}
	style={`--beam-color: ${color}; --beam-radius: ${radius}px; --beam-intensity: ${intensity}; --beam-x: ${x}%; --beam-y: ${y}%`}
	on:pointermove={updatePosition}
	on:pointerleave={() => (engaged = false)}
	on:focusin={focusPosition}
	on:focusout={() => (engaged = false)}
>
	<div class="beam" aria-hidden="true" />
	<div class="content"><slot /></div>
</div>

<style>
	.focus-beam {
		position: relative;
		overflow: hidden;
		isolation: isolate;
	}

	.beam {
		position: absolute;
		z-index: -1;
		inset: 0;
		background: radial-gradient(
			circle var(--beam-radius) at var(--beam-x) var(--beam-y),
			color-mix(in srgb, var(--beam-color) calc(var(--beam-intensity) * 100%), transparent),
			transparent 70%
		);
		opacity: 0.45;
		transition: opacity 320ms ease;
	}

	.engaged .beam,
	.focus-beam:focus-within .beam {
		opacity: 1;
	}

	.content {
		position: relative;
		z-index: 1;
	}

	@media (prefers-reduced-motion: reduce) {
		.beam {
			transition: none;
		}
	}
</style>

// src/components/beautiful/focus-beam/focus-beam.tsx
'use client';

import {
	useEffect,
	useRef,
	type FocusEvent,
	type HTMLAttributes,
	type PointerEvent,
	type ReactNode
} from 'react';
import type { CustomProperties } from '../types';
import './focus-beam.css';

export type FocusBeamProps = HTMLAttributes<HTMLDivElement> & {
	children: ReactNode;
	color?: string;
	radius?: number;
	intensity?: number;
};

export function FocusBeam({
	children,
	color = '#405cff',
	radius = 260,
	intensity = 0.18,
	className = '',
	style,
	...props
}: FocusBeamProps) {
	const hostRef = useRef<HTMLDivElement>(null);
	const frameRef = useRef<number | null>(null);
	const pendingPointer = useRef({ x: 0, y: 0 });
	const pointerEngaged = useRef(false);
	const focusEngaged = useRef(false);
	const beamStyle: CustomProperties = {
		'--beam-color': color,
		'--beam-radius': `${Math.max(1, radius)}px`,
		'--beam-intensity': Math.max(0, Math.min(1, intensity)),
		'--beam-x': '50%',
		'--beam-y': '50%',
		...style
	};

	useEffect(
		() => () => {
			if (frameRef.current !== null) cancelAnimationFrame(frameRef.current);
		},
		[]
	);

	function syncEngagement() {
		if (hostRef.current) {
			hostRef.current.dataset.engaged = `${pointerEngaged.current || focusEngaged.current}`;
		}
	}

	function setPosition(clientX: number, clientY: number) {
		const host = hostRef.current;
		if (!host) return;
		const bounds = host.getBoundingClientRect();
		host.style.setProperty('--beam-x', `${((clientX - bounds.left) / bounds.width) * 100}%`);
		host.style.setProperty('--beam-y', `${((clientY - bounds.top) / bounds.height) * 100}%`);
	}

	function handlePointerMove(event: PointerEvent<HTMLDivElement>) {
		pendingPointer.current = { x: event.clientX, y: event.clientY };
		pointerEngaged.current = true;
		syncEngagement();
		if (frameRef.current !== null) return;
		frameRef.current = requestAnimationFrame(() => {
			setPosition(pendingPointer.current.x, pendingPointer.current.y);
			frameRef.current = null;
		});
	}

	function handleFocus(event: FocusEvent<HTMLDivElement>) {
		const host = hostRef.current;
		if (!host || !(event.target instanceof HTMLElement)) return;
		const targetBounds = event.target.getBoundingClientRect();
		setPosition(
			targetBounds.left + targetBounds.width / 2,
			targetBounds.top + targetBounds.height / 2
		);
		focusEngaged.current = true;
		syncEngagement();
	}

	function handleBlur(event: FocusEvent<HTMLDivElement>) {
		if (event.relatedTarget instanceof Node && hostRef.current?.contains(event.relatedTarget))
			return;
		focusEngaged.current = false;
		syncEngagement();
	}

	return (
		<div
			ref={hostRef}
			className={`bc-focus-beam ${className}`.trim()}
			style={beamStyle}
			data-engaged="false"
			onPointerMove={handlePointerMove}
			onPointerLeave={() => {
				pointerEngaged.current = false;
				syncEngagement();
			}}
			onFocus={handleFocus}
			onBlur={handleBlur}
			{...props}
		>
			<div className="bc-focus-beam__field" aria-hidden="true" />
			<div className="bc-focus-beam__content">{children}</div>
		</div>
	);
}
